DROP TABLE IF EXISTS reports;
DROP TABLE IF EXISTS evidence;
DROP TABLE IF EXISTS findings;
DROP TABLE IF EXISTS assets;
DROP TABLE IF EXISTS scans;
DROP TABLE IF EXISTS targets;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS users;
